export const MenuList = [{
  key: 'Index',
  path: '/Index',
  name: '首页',
  icon: 'home',
  MenuList: [{
    type: "2",
    key: 'Home',
    path: '/Home',
    name: '首页',
  }]
}, {
  key: 'StoreManage',
  path: '/StoreManage',
  name: '门店管理',
  icon: 'shop',
  MenuList: [{
    type: "2",
    key: 'Store',
    path: '/Store',
    name: '门店管理',
  }]
}, {
  key: 'Member',
  path: '/Member',
  name: '用户管理',
  icon: 'user',
  MenuList: [{
    type: "1",
    key: 'UserList',
    path: 'UserList',
    name: '用户列表',
  }, {
    type: "1",
    key: 'OrderList',
    path: 'OrderList',
    name: '订单列表',
  }, {
    type: "1",
    key: 'GroupList',
    path: 'GroupList',
    name: '用户组别',
  }, {
    type: "1",
    key: 'TagList',
    path: 'TagList',
    name: '用户标签',
  }]
}, {
  key: 'Tweets',
  path: '/Tweets',
  name: '推文管理',
  icon: 'book',
  MenuList: [{
    type: "1",
    key: 'ImageText',
    path: '/ImageText',
    name: '图文管理',
  }, {
    type: "1",
    key: 'Picture',
    path: '/Picture',
    name: '图片管理',
  }, {
    type: "1",
    key: 'TypesList',
    path: '/TypesList',
    name: '分类管理',
  }, {
    type: "1",
    key: 'Auditing',
    path: '/Auditing',
    name: '审核列表',
  }]
}, {
  key: 'Message',
  path: '/Message',
  name: '消息中心',
  icon: 'message',
  MenuList: [{
    type: "1",
    key: 'GroupSend',
    path: '/GroupSend',
    name: '群发素材',
  }, {
    type: "2",
    key: 'Wechat',
    path: '/Wechat',
    name: '微信配置',
    MenuList: [{
      type: "1",
      key: 'WechatMenu',
      path: '/WechatMenu',
      name: '菜单列表',
    }, {
      type: "1",
      key: 'Keyword',
      path: '/Keyword',
      name: '关键词回复',
    }, {
      type: "1",
      key: 'FollowReply',
      path: '/FollowReply',
      name: '被关注回复',
    }]
  }, {
    type: "1",
    key: 'GroupMessage',
    path: '/GroupMessage',
    name: '群发短信',
  }]
}, {
  key: 'System',
  path: '/System',
  name: '系统管理',
  icon: 'setting',
  MenuList: [{
    type: "1",
    key: 'Account',
    path: '/Account',
    name: '账号管理',
  }, {
    type: "1",
    key: 'Role',
    path: '/Role',
    name: '角色管理',
  }, {
    type: "1",
    key: 'PowerPoints',
    path: '/PowerPoints',
    name: '功能点管理',
  }, {
    type: "1",
    key: 'SmsConfig',
    path: '/SmsConfig',
    name: '短信配置管理',
  }]
}];
